#!/bin/bash
## FILENAME:  myjobsubmissionfile
#
#SBATCH -A multiscaleml      # allocation name
#SBATCH --nodes=1           # Total # of nodes 
#SBATCH -n 1             # Total # of nodes 
#SBATCH --time=124:00:00        # Total run time limit (hh:mm:ss)
#SBATCH -J job          # Job name         # Name of stderr error file
#SABTCH -C 'amd20'
#SBATCH --mem-per-cpu=4G

module restore plumed2_torch
conda activate pytorch_18
source  /mnt/research/MultiscaleML_group/Liyao/plumed/sourceme5.sh 
/mnt/home/lyuliyao/gromacs_2020/bin/gmx_mpi mdrun -s ./chi1.tpr  -plumed ./plumed1.dat -ntomp 1 -nsteps 100  -c conf.gro -nb cpu
python3 consensus.py --N_iter 21 --dim 3 --nesm 20 --clean True
sacct --format=JobID,Submit,Partition,CPUTime,Elapsed,MaxRSS,NodeList,ReqCPUS --units=M -j $SLURM_JOBID
