#!/bin/bash
## FILENAME:  myjobsubmissionfile
#
#SBATCH -A multiscaleml      # allocation name
#SBATCH --nodes=1           # Total # of nodes 
#SBATCH -n 1             # Total # of nodes 
#SBATCH --time=48:00:00        # Total run time limit (hh:mm:ss)
#SBATCH -J job          # Job name         # Name of stderr error file
#SABTCH -C 'amd20'
#SBATCH --mem-per-cpu=48G

module restore plumed2_torch
conda activate plumed2torch
source  /mnt/research/MultiscaleML_group/Liyao/plumed/sourceme6.sh 
mpirun -n 1 /mnt/home/lyuliyao/gromacs_2023/bin/gmx mdrun -s ala2.tpr -plumed plumed.dat -nsteps $1 
plumed driver --plumed plmd-reweight.dat --itrr traj.trr 
sacct --format=JobID,Submit,Partition,CPUTime,Elapsed,MaxRSS,NodeList,ReqCPUS --units=M -j $SLURM_JOBID
