#!/bin/bash
## FILENAME:  myjobsubmissionfile
#
#SBATCH -A multiscaleml      # allocation name
#SBATCH --nodes=1           # Total # of nodes 
#SBATCH -n 4             # Total # of nodes 
#SBATCH --time=120:00:00        # Total run time limit (hh:mm:ss)
#SBATCH -J job          # Job name         # Name of stderr error file
#SABTCH -C 'amd20'
#SBATCH --mem-per-cpu=48G
module restore plumed2_torch
conda activate plumed2torch
source  /mnt/research/MultiscaleML_group/Liyao/plumed/sourceme5.sh 
source /mnt/home/lyuliyao/gromacs_2020/bin/GMXRC.bash
# plumed sum_hills --hills HILLS --outfile fes.dat --bin 89,89
mpirun -n 1 /mnt/home/lyuliyao/gromacs_2020/bin/gmx_mpi mdrun -s ala2.tpr -plumed plmd-ala2_ref.dat -nsteps 5000000
